name: Multistage S3 Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-preprod:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Deploy Preprod
      uses: reggionick/s3-deploy@v3
      with:
        folder: website
        bucket: ${{ secrets.S3_BUCKET_PREPROD }}
        bucket-region: ${{ secrets.S3_BUCKET_REGION }}
        dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PREPROD }}
        invalidation: /
        delete-removed: true
        no-cache: true
        private: true

  deploy-prod:
    runs-on: ubuntu-latest
    needs: [deploy-preprod]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Deploy Prod
      uses: reggionick/s3-deploy@v3
      with:
        folder: website
        bucket: ${{ secrets.S3_BUCKET_PROD }}
        bucket-region: ${{ secrets.S3_BUCKET_REGION }}
        dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }}
        invalidation: /
        delete-removed: true
        no-cache: true
        private: true
